---
- name: Setup localhost
  tags: ['host']
  block:
    - name: Set hostname
      ansible.builtin.hostname:
        name: '{{ hostname }}'

    - name: Copy /etc/hosts with localhost definitions
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
