---
- name: Add locales
  tags: ['localization']
  block:
    - name: Enable en_US.UTF-8 locale
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Enable ru_RU.UTF-8 locale
      community.general.locale_gen:
        name: ru_RU.UTF-8
        state: present
