---
- name: System upgrade
  tags: ['always']
  community.general.pacman:
    update_cache: true
    upgrade: true

- include_tasks: user.yml
  tags: ['user']
- include_tasks: localization.yml
  tags: ['localization']
- include_tasks: host.yml
  tags: ['host']
