---
- name: System upgrade
  tags: ['always']
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Setup user account
  tags: ['user']
  ansible.builtin.include_tasks: user.yml
- name: Setup localization
  tags: ['localization']
  ansible.builtin.include_tasks: localization.yml
- name: Setup localhost
  tags: ['host']
  ansible.builtin.include_tasks: host.yml
