---
- name: Install sudo
  pacman:
    name: sudo
    state: present

- name: Copy sudoers file
  copy:
    src: sudoers
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'

- name: Create user group
  group:
    name: '{{ username }}'
    state: present

- name: Create user
  user:
    name: '{{ username }}'
    comment: '{{ fullname }}'
    password: '{{ password }}'
    groups: wheel, audio, disk, input, storage, '{{ username }}'
    create_home: true
