---
- name: Copy pacman config
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    mode: 0644
    owner: root
    group: root

- name: System upgrade
  pacman:
    upgrade: true
    update_cache: true

- include_tasks: paccache.yml
- include_tasks: yay.yml
