---
- name: Install rate-mirrors
  community.general.pacman:
    name: rate-mirrors
    state: present
    executable: yay
  become_user: '{{ username }}'

- name: Backup mirror list
  ansible.builtin.copy:
    src: /etc/pacman.d/mirrorlist
    dest: /etc/pacman.d/mirrorlist.backup
    mode: 0644
    owner: root
    group: root

- name: Run rate-mirrors
  ansible.builtin.command:
    cmd: 'rate-mirrors arch --save /etc/pacman.d/mirrorlist'
    creates: /etc/pacman.d/mirrorlist
