---
- name: Install pacman-contrib
  pacman:
    name: pacman-contrib
    state: present

- name: Create pacman hooks dir
  file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: 0744

- name: Copy paccache hooks
  copy:
    src: '{{ item }}'
    dest: /etc/pacman.d/hooks/
    mode: 0644
    owner: root
    group: root
  with_items:
    - paccache.hook
    - paccache_deleted.hook
