---
- name: Install pacman-contrib
  pacman:
    name: pacman-contrib
    state: present

- name: Copy paccache hooks
  copy:
    src: '{{ item }}'
    dest: /etc/pacman.d/hooks/
    mode: 0644
    owner: root
    group: root
  with_items:
    - paccache.hook
    - paccache_deleted.hook
