---
- name: Install pacman-contrib
  pacman:
    name: pacman-contrib
    state: present

- name: Create pacman hooks dir
  file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: 0744

- name: Copy paccache hook
  copy:
    src: paccache.hook
    dest: /etc/pacman.d/hooks/paccache.hook
    mode: 0644
    owner: root
    group: root

- name: Copy paccache hook for deleted packages
  copy:
    src: paccache_deleted.hook
    dest: /etc/pacman.d/hooks/paccache_deleted.hook
    mode: 0644
    owner: root
    group: root
