---
- name: Install yay AUR helper
  tags: ['aur']
  block:
    - name: Install base-devel package group
      pacman:
        name: base-devel
        state: present

    - name: Get latest yay tag from GitHub
      ansible.builtin.uri:
        url: 'https://api.github.com/repos/Jguer/yay/releases/latest'
        return_content: true
      register: yay_latest

    - name: Download latest yay
      ansible.builtin.unarchive:
        remote_src: true
        src: "https://github.com/Jguer/yay/releases/download/{{ yay_latest.json.tag_name }}\
          /yay_{{ yay_latest.json.tag_name | regex_replace('^v','') }}_x86_64.tar.gz"
        dest: /tmp
        mode: 0744
        keep_newer: true
        extra_opts:
          - --no-anchored
          - yay

    - name: Install yay
      ansible.builtin.command:
        chdir: "/tmp/yay_{{ yay_latest.json.tag_name | regex_replace('^v','') }}_x86_64"
        cmd: "./yay -S yay --noconfirm"
      register: yay_result
      changed_when: yay_result.stdout != "0"
