---
- name: Install base-devel group
  pacman:
    name: base-devel
    state: present

- name: Clone AUR yay repo
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    version: master
  become_user: '{{ username }}'

- name: Build yay
  command:
    chdir: /tmp/yay
    cmd: 'makepkg --syncdeps'
    creates: 'yay-*.pkg.tar.zst'
  become_user: '{{ username }}'

#- name: Install yay
