---
# Taking inspiration from https://github.com/wshanks/ansible-fedora/blob/master/tasks/partial_ini.yml
- name: 'Set config: {{ ini.path }}'
  community.general.ini_file:
    path: '/home/{{ username }}/.config/{{ ini.path }}'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    mode: '0600'
    owner: '{{ username }}'
    group: '{{ username }}'
  loop: "{{ query('lookup_ini', '.config/' + ini.path) }}"
