---
- name: Install KDE Plasma
  community.general.pacman:
    name:
      - plasma
      - kde-gtk-config
      - breeze-gtk
      - kdeplasma-addons
      - kdeconnect
      - sshfs
      - powerdevil
    state: present

- name: Install UI fonts
  community.general.pacman:
    name:
      - inter-font
      - ttf-jetbrains-mono
    state: present

# - name: Set configs
#   include_tasks: configs.yml
#   loop: "{{ query('filetree', '.config') }}"
#   loop_control:
#     loop_var: ini
