---
- name: Install KDE Plasma
  pacman:
    name: plasma
    state: present

- name: Install SDDM
  pacman:
    name:
      - sddm
      - sddm-kcm
    state: present

- name: Enable SDDM
  systemd:
    name: sddm
    enabled: true
