---
- name: Setup Display Manager
  ansible.builtin.include_tasks: sddm.yml
- name: Setup Desktop Environment
  ansible.builtin.include_tasks: kde.yml

- name: Install packages for consistent file dialog
  community.general.pacman:
    name:
      - xdg-desktop-portal
      - xdg-desktop-portal-kde
    state: present

- name: Set ENV variable for consistent file dialog
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: GTK_USE_PORTAL=1
    state: present
    create: true
    mode: '0600'
    owner: root
    group: root
