---
- name: Install compilers/intepreters and necessary instuments
  tags: ['development', 'cli']
  block:
    - name: Install Python tools
      tags: ['python']
      pacman:
        name:
          - python
          - python-poetry
          - ipython
        state: present

    - name: Install C/C++ tools
      tags: ['c', 'cpp']
      pacman:
        name:
          - gcc
          - gdb
          - make
          - cmake
        state: present

    - name: Install JavaScript tools
      tags: ['js']
      pacman:
        name:
          - npm
          - nodejs
        state: present

    - name: Install Java tools
      pacman:
        name:
          - jre-openjdk
          - maven
        state: present

- name: Install IDEs
  tags: ['development', 'gui']
  block:
    - name: Install PyCharm
      tags: ['python']
      pacman:
        name: pycharm-community-edition
        state: present

    - name: Install VS Code
      tags: ['c', 'cpp', 'js']
      pacman:
        name: code
        state: present

    - name: Install Intellij IDEA
      tags: ['java']
      pacman:
        name: intellij-idea-community-edition
        state: present

- name: Install additional GUI tools
  tags: ['development', 'gui']
  block:
    - name: Install browsers
      tags: ['js']
      pacman:
        name:
          - firefox
          - chromium
        state: present
